version: "3"
services:
    frontend:
      build:
        context: "./frontend"
      ports:
        - "3000:3000"
      volumes:
        - "./frontend:/app"

    #backend:
    #  build:
    #    context: "./backend"
    #  volumes:
    #    "./backend:/app"
    #  ports:
    #    - "8000:8000"